# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_args_CensusBase__initialize <- function(api_key, base_url, async) {
  assert_scalar_character(api_key)
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  return(invisible(NULL))
}

assert_return_CensusBase__initialize <- function(value) {
  assert_class(value, "CensusBase")
  return(value)
}

assert_args_CensusEconomicIndicators__get_series <- function(program, category_code, data_type_code, time, seasonally_adj, geo_for) {
  assert_scalar_character(program)
  if (!is.null(category_code)) {
    assert_scalar_character(category_code)
  }
  if (!is.null(data_type_code)) {
    assert_scalar_character(data_type_code)
  }
  if (!is.null(time)) {
    assert_scalar_character(time)
  }
  if (!is.null(seasonally_adj)) {
    assert_scalar_character(seasonally_adj)
    assert_value_in_set(seasonally_adj, c("yes", "no"))
  }
  assert_scalar_character(geo_for)
  return(invisible(NULL))
}

assert_return_CensusEconomicIndicators__get_series <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("program", "category_code", "data_type_code", "seasonally_adj", "datetime", "time_slot_name", "cell_value", "error_data", "geo_level"))
  assert_character(value[["program"]])
  assert_no_missing_values(value[["program"]])
  assert_character(value[["category_code"]])
  assert_no_missing_values(value[["category_code"]])
  assert_character(value[["data_type_code"]])
  assert_no_missing_values(value[["data_type_code"]])
  assert_character(value[["seasonally_adj"]])
  assert_no_missing_values(value[["seasonally_adj"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_character(value[["time_slot_name"]])
  assert_no_missing_values(value[["time_slot_name"]])
  assert_double(value[["cell_value"]])
  assert_character(value[["error_data"]])
  assert_character(value[["geo_level"]])
  assert_no_missing_values(value[["geo_level"]])
  return(value)
}

assert_args_census_backfill_series <- function(program, from, to, category_code, data_type_code, seasonally_adj, geo_for, api_key, base_url, sleep) {
  assert_scalar_character(program)
  assert_scalar_count(from)
  assert_between(from, lower = 1900)
  assert_scalar_count(to)
  assert_between(to, lower = 1900)
  if (!is.null(category_code)) {
    assert_scalar_character(category_code)
  }
  if (!is.null(data_type_code)) {
    assert_scalar_character(data_type_code)
  }
  if (!is.null(seasonally_adj)) {
    assert_scalar_character(seasonally_adj)
    assert_value_in_set(seasonally_adj, c("yes", "no"))
  }
  assert_scalar_character(geo_for)
  assert_scalar_character(api_key)
  assert_scalar_character(base_url)
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_census_backfill_series <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("program", "category_code", "data_type_code", "seasonally_adj", "datetime", "time_slot_name", "cell_value", "error_data", "geo_level"))
  assert_character(value[["program"]])
  assert_no_missing_values(value[["program"]])
  assert_character(value[["category_code"]])
  assert_no_missing_values(value[["category_code"]])
  assert_character(value[["data_type_code"]])
  assert_no_missing_values(value[["data_type_code"]])
  assert_character(value[["seasonally_adj"]])
  assert_no_missing_values(value[["seasonally_adj"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_character(value[["time_slot_name"]])
  assert_no_missing_values(value[["time_slot_name"]])
  assert_double(value[["cell_value"]])
  assert_character(value[["error_data"]])
  assert_character(value[["geo_level"]])
  assert_no_missing_values(value[["geo_level"]])
  return(value)
}

assert_args_census_base_url <- function(url) {
  assert_scalar_character(url)
  return(invisible(NULL))
}

assert_return_census_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_census_catalogue_url <- function(url) {
  assert_scalar_character(url)
  return(invisible(NULL))
}

assert_return_census_catalogue_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_return_census_api_key <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_census_datasets <- function(catalogue_url, async) {
  assert_scalar_character(catalogue_url)
  assert_scalar_logical(async)
  return(invisible(NULL))
}

assert_return_census_datasets <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("identifier", "title", "program_path", "vintage", "is_microdata", "is_timeseries", "variables_link", "geography_link"))
  assert_character(value[["identifier"]])
  assert_no_missing_values(value[["identifier"]])
  assert_character(value[["title"]])
  assert_no_missing_values(value[["title"]])
  assert_character(value[["program_path"]])
  assert_no_missing_values(value[["program_path"]])
  assert_integer(value[["vintage"]])
  assert_logical(value[["is_microdata"]])
  assert_no_missing_values(value[["is_microdata"]])
  assert_logical(value[["is_timeseries"]])
  assert_no_missing_values(value[["is_timeseries"]])
  assert_character(value[["variables_link"]])
  assert_no_missing_values(value[["variables_link"]])
  assert_character(value[["geography_link"]])
  assert_no_missing_values(value[["geography_link"]])
  return(value)
}

assert_args_census_variables <- function(dataset_path, base_url, async) {
  assert_scalar_character(dataset_path)
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  return(invisible(NULL))
}

assert_return_census_variables <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("name", "label", "concept", "predicate_type", "required", "group"))
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["label"]])
  assert_no_missing_values(value[["label"]])
  assert_character(value[["concept"]])
  assert_character(value[["predicate_type"]])
  assert_logical(value[["required"]])
  assert_no_missing_values(value[["required"]])
  assert_character(value[["group"]])
  return(value)
}

assert_args_census_geographies <- function(dataset_path, base_url, async) {
  assert_scalar_character(dataset_path)
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  return(invisible(NULL))
}

assert_return_census_geographies <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("geo_level", "name", "requires"))
  assert_character(value[["geo_level"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["requires"]])
  return(value)
}

assert_return_empty_dt_eits_series <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("program", "category_code", "data_type_code", "seasonally_adj", "datetime", "time_slot_name", "cell_value", "error_data", "geo_level"))
  assert_character(value[["program"]])
  assert_no_missing_values(value[["program"]])
  assert_character(value[["category_code"]])
  assert_no_missing_values(value[["category_code"]])
  assert_character(value[["data_type_code"]])
  assert_no_missing_values(value[["data_type_code"]])
  assert_character(value[["seasonally_adj"]])
  assert_no_missing_values(value[["seasonally_adj"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_character(value[["time_slot_name"]])
  assert_no_missing_values(value[["time_slot_name"]])
  assert_double(value[["cell_value"]])
  assert_character(value[["error_data"]])
  assert_character(value[["geo_level"]])
  assert_no_missing_values(value[["geo_level"]])
  return(value)
}

assert_return_empty_dt_dataset_catalogue <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("identifier", "title", "program_path", "vintage", "is_microdata", "is_timeseries", "variables_link", "geography_link"))
  assert_character(value[["identifier"]])
  assert_no_missing_values(value[["identifier"]])
  assert_character(value[["title"]])
  assert_no_missing_values(value[["title"]])
  assert_character(value[["program_path"]])
  assert_no_missing_values(value[["program_path"]])
  assert_integer(value[["vintage"]])
  assert_logical(value[["is_microdata"]])
  assert_no_missing_values(value[["is_microdata"]])
  assert_logical(value[["is_timeseries"]])
  assert_no_missing_values(value[["is_timeseries"]])
  assert_character(value[["variables_link"]])
  assert_no_missing_values(value[["variables_link"]])
  assert_character(value[["geography_link"]])
  assert_no_missing_values(value[["geography_link"]])
  return(value)
}

assert_return_empty_dt_variable_dictionary <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("name", "label", "concept", "predicate_type", "required", "group"))
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["label"]])
  assert_no_missing_values(value[["label"]])
  assert_character(value[["concept"]])
  assert_character(value[["predicate_type"]])
  assert_logical(value[["required"]])
  assert_no_missing_values(value[["required"]])
  assert_character(value[["group"]])
  return(value)
}

assert_return_empty_dt_geography_list <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("geo_level", "name", "requires"))
  assert_character(value[["geo_level"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["requires"]])
  return(value)
}

assert_args_census_sign_key <- function(req, keys) {
  assert_class(req, "httr2_request")
  assert_list(keys)
  return(invisible(NULL))
}

assert_return_census_sign_key <- function(value) {
  assert_class(value, "httr2_request")
  return(value)
}

assert_args_parse_census_response <- function(resp) {
  assert_class(resp, "httr2_response")
  return(invisible(NULL))
}

assert_return_parse_census_response <- function(value) {
  if (!is.null(value)) {
    assert_list(value)
  }
  return(value)
}

